---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodejsapp
  name: nodejsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejsapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejsapp
    spec:
      containers:
      - image: kubenodejsacr.azurecr.io/lab3kubenode:latest
        name: nodejsapp1
        imagePullPolicy: Always
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nodejsapp
  name: nodejsapp
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: nodejsapp
  type: LoadBalancer
status:
  loadBalancer: {}